### ISSUE TITLE
10th March 2020

### ISSUE THREAD

**Issue by Jmagero** [SevlaMare/newsweek-clone#2]
Add issues here

**Comment by harshdeepkanhai** [comment]
![image](https://user-images.githubusercontent.com/61924625/76322579-95f5f080-6309-11ea-8d6e-2817bb79a8cf.png)
Don't use important here try some other fix in bootstrap only

**Comment by harshdeepkanhai** [comment]
You are not using the class bg-red remove the css file as you are not using it.
